### ISSUE TITLE
Защита от DDoS

### ISSUE THREAD

**Issue by Antonische** [CinemaPress/CinemaPress-CMS#2]
Добрый день.

Сделал сайт на демке, запретил индексирование и начал рерайтить описания к фильмам и прописывать названия в конфигах. Сайт стал недоступен, хост говорит что под атакой.

Можете как-то помочь?

**Comment by extensionsapp** [comment]
Здравствуйте.

Откройте терминал сервера и выполните команду:

```
cd /var/log && du -h * | sort -h
```

Вряд ли это целенаправленная атака, а просто боты перебирают адреса и брутят 22 порт.
Видите, большие размеры файлов auth, btmp, ...?

**Comment by Antonische** [comment]
Большие?

356K    nginx
504K    auth.log.2.gz
868K    auth.log.4.gz
1.1M    auth.log.3.gz
14M     auth.log
14M     installer
14M     installer/cdebconf
16M     auth.log.1
131M    btmp.1

**Comment by extensionsapp** [comment]
Новая версия CinemaPress содержит минимальную защиту, можете переустановить или выполнить команды:

```
apt-get install fail2ban
wget https://raw.githubusercontent.com/CinemaPress/CinemaPress-CMS/master/config/jail.conf
cp jail.conf /etc/fail2ban/jail.local
service fail2ban restart
```

Это поможет не обращать внимания на случайные атаки на FTP, SSH и админ-панель.

**Comment by Antonische** [comment]
Спасибо за быструю реакцию.

![ddos](https://cloud.githubusercontent.com/assets/17744814/14210135/5373432c-f830-11e5-8b99-509c96e6deec.png)
