### ISSUE TITLE
Комплексная установка Memcached серверов

### ISSUE THREAD

**Issue by jamatos** [CinemaPress/CinemaPress-CMS#3]
Здравствуйте.

Есть несколько сайтов, они все на разных серверах, однако у них один Memcached сервер. Сегодня пришло "письмо счастья" от хостера, они случайно переустановили ОС на Memcached  сервере. Возмещение возмещением, но теперь мне нужно заново устанавливать Memcached сервера для сайтов, коих достаточно много (24 шт.).

Есть какое-то решение, чтобы быстро это сделать?

**Comment by extensionsapp** [comment]
В следующем обновлении будут добавлены массовые действия.

**Comment by extensionsapp** [comment]
Добавлено:
``8) Массовая установка/обновление/добавление``
Функция тестируется, а пока можете изучить[ документацию](https://github.com/CinemaPress/CinemaPress-CMS/wiki/%D0%9C%D0%B0%D1%81%D1%81%D0%BE%D0%B2%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5).

**Comment by jamatos** [comment]
Спасибо, я не дождался и уже создал сервер поочередно для каждого сайта, но теперь рад что есть такое решение!

**Comment by extensionsapp** [comment]
Функция протестирована и работает исправно.

**Comment by jamatos** [comment]
Здравствуйте.

Посмотрел документацию, но есть одна проблема. При переносе всех сайтов с одного сервера на другой, config файл то всё равно придется вручную переносить, сделайте чтобы переносилось автоматом вместе с config.js файлом.

Спасибо.

**Comment by extensionsapp** [comment]
@jamatos да, уже работаем над созданием автоматического резервного копирования.
